### ISSUE TITLE
Error: Ledger device is unavailable

### ISSUE THREAD

**Issue by kerner1000** [atomiclabs/ledger-kmd-reward-claim#22]
I cannot connect to my Ledger device.

Steps to reproduce:
1) Start Ledger device, oben the Komodo app.
2) Open https://atomiclabs.github.io/ledger-kmd-reward-claim/. (Tested with Firefox and Chrome)
3) Click "Check Rewards"
4) Get "unavailable" error.

![unavailable](https://user-images.githubusercontent.com/13817521/74348061-67403500-4db2-11ea-89c4-06e823e52ed7.png)

I can connect other usb-apps, such as the "TronWalletPlay" or "Ledger Live Desktop" app, so I assume the usb-connection is working in principle.

```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.04
DISTRIB_CODENAME=disco
DISTRIB_DESCRIPTION="Ubuntu 19.04"
```

**Comment by Dectman** [comment]
Same problem....updated firmware but that did not help

**Comment by kerner1000** [comment]
Tried again, now I get #21 
> Error
Bitcoin JSON-RPC: Request Error: connect ECONNREFUSED 127.0.0.1:8232

**Comment by ghost** [comment]
Error
Bitcoin JSON-RPC: Request Error: connect ECONNREFUSED 127.0.0.1:8232

<img width="634" alt="Снимок экрана 2020-02-27 в 09 59 12" src="https://user-images.githubusercontent.com/18265958/75419925-ef444400-5947-11ea-97eb-22ca59801647.png">

**Comment by lukechilds** [comment]
The issue should now be resolved: https://github.com/atomiclabs/ledger-kmd-reward-claim/issues/21#issuecomment-591851710

**Comment by Dectman** [comment]
Still not working for me.....error exporting and ledger device unavailable

**Comment by ghost** [comment]
@Dectman update Ledger Komodo app on your device

**Comment by Dectman** [comment]
just updated drivers, 1.3.21; did not work. Keeps saying "could not complete sign in" and then later device unavailable

**Comment by ghost** [comment]
@Dectman On your device, in Komodo app. Settings->Public keys export->Auto Approval

**Comment by Dectman** [comment]
appreciate the help. I put it on auto approval but that did not work...it tries couple of times in sequence but fails every time. Tried 2 different browsers and different cables. Would be weird if it's only me so i'll keep an eye out on Github if more reports come in.

**Comment by ghost** [comment]
It’s work only Google Chrome

**Comment by Dectman** [comment]
i always used to claim fine in Firefox. Tried Chrome just now, same result
